"""empty message

Revision ID: 59265f912c0d
Revises: 
Create Date: 2018-04-30 02:04:49.964661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59265f912c0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'follower_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('follows', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'follows', 'users', ['user_id'], ['id'])
    op.alter_column('likes', 'post_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('likes', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['postid'])
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    op.alter_column('posts', 'caption',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'created_on',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'biography',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'joined_on',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'profile_photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'profile_photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'joined_on',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'biography',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'created_on',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'caption',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.alter_column('likes', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('likes', 'post_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.alter_column('follows', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('follows', 'follower_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
